export enum RadixAtomNodeStatus {
    PENDING = 'PENDING',
    SUBMITTING = 'SUBMITTING',
    SUBMITTED = 'SUBMITTED',
    STORED = 'STORED',
    EVICTED_CONFLICT_LOSER = 'EVICTED_CONFLICT_LOSER',
    EVICTED_FAILED_CM_VERIFICATION = 'EVICTED_FAILED_CM_VERIFICATION',
    MISSING_DEPEPENDENCY = 'MISSING_DEPEPENDENCY',
    CONFLICT_LOSER = 'CONFLICT_LOSER',
    STORED_FINAL = 'STORED_FINAL',
    EVICTED_CONFLICT_LOSER_FINAL = 'EVICTED_CONFLICT_LOSER_FINAL',
}
