language: node_js
node_js: node
dist: trusty

services:
  - docker

addons:
  sonarcloud:
    organization: "radixdlt-github"
    token:
      secure: "f5iEJcPVA0EC47s3Gv4qe1eqqEnrZQDIB2FCiEnOcu5UEw+h3J9zyxo2Ebk0b4/tdvbGdSVetvQ7KoXC6TJ444UfyqHAfmJOCIZ/Lxi9b4CmwmkAgd8OuAGqILnrZIrbmICTVojg0xpf10fK8fcdo86DXM8x3LmkLjGud9BRItwNMKGFrClv9aCi7rcxTZnki2OLNRJv8ll9adzJDdpj7B4DxiLxrDdOz9qudabDLCsxZyIkaTknz7e0wYmKjV9HeF+Jd8SS9qb1BaRabMtSHO6RcIZcm7nseLW7y0mDIyzuvBq4EPLG3DWLhtsIPvxl2FjEMJc4/6oAAVdlT4YSxbmdI8vY4HUHKpCR//JHtlbold7Po3kt7m3JxOXUN524DVI0HoCI5k6fYL3cRwIJ0l5emsb2YkuW8nriqiB6QBsLKhN4fXlVThYfQfB1CBfeJX1w6Bu/VjL7m04LOOBTyIu40Dv9omIytEfhR8JdNybGz4V3OwfM/5m5dWXadP52e1UsRuuyRQhWksb/NhQrv8jMmTSKPFu0xgRDsdo1E6bLIy0bz2ul8CyoGtfx4dIoL3ACrsRKwS5LbrpmkKTzwLY0OcBxW5Q3fDstNrPsCtnjrbiTJEM4kycnvgLdIa/pdLxTMV9cHn5A4OV+nGsWNa620aajxaUkJ3zNRIiSIs0="

before_install:
  # Run
  - docker build -t radixdlt-js .
  #  SetUp infrastructure for integration tests
  - docker-compose -f .travisci/minimal-network.yml pull
  - docker-compose -f .travisci/minimal-network.yml up -d
  - docker stop radixdlt-js || true && docker rm radixdlt-js || true

script:
  #  Run unit and integration tests
  - docker run --network host --name radixdlt-js radixdlt-js yarn test:unit && yarn test:integration

after_success:
  # Static analyzers
  - yarn coverage
  - sonar-scanner
