language: node_js
node_js: node
dist: trusty

services:
  - docker

addons:
  sonarcloud:
    organization: "radixdlt-github"
    token:
      secure: "AiOtmnvEKa4nrMj8s++rcHGxcJV+BJY7TBU9HQ/CKrx16Z5U/C1le+JUCmaHIYLV3XlRE59c5zUZMk8c+fET8laQrjRgLIVPGNEyJyhHEzc/Ou5dsN87obYEFfNpV2zZ8zsLsRddaW9SGR4yPYjMZi8jVaGL3yNLIGEO31KpcrtPmjpdad0dFtIj4bFLTSoW6JwaJ6DzwfEoHFjaFYVhpIz518IfbtBITx8fxip4lJzPh8or/Vw+cW4SaPzXaqmCsor2QQQIi2ZDgqqvxr67JGBdBb/Uwax8T4sgGwQkNjWzAVu2hlks8DLu5a/WLOQsGlgP0ixUFpP64qW5aDEcJ04/67tOPUpNeY5A8UShUrlFsdykDSJbeLlLiJUoq9+sNe3up3XGnQfv8AIB0+wB6pQbPwgyQ2tZ2v7DV9s+46StpmhAeNNoPnN1O3NTiU3UuXvWR3eKNh4VzsbTVQ9W3ZPMymAHFaQwlkf9y15ZOCPxKkt6VAyPwftl0VT7rYrNs8HjKn5LWMexB2MRwjtAofiR84h5Hesqjk/jeWW9XebHSVj2IxTaRH26SsHqMJikwZEh6Zr0sfBKZDnxMjLK/Zi2KWOMb3mvylmx/zPVJA1VkJ1JhwBxTW78Hd83sIymEfhDIRjq3EJKKw6ZkIwczuc4SV2afoxeDOV4y3jnv9k="

before_install:
  # Run
  - docker build -t radixdlt-js .
  #  SetUp infrastructure for integration tests
  - docker-compose -f .travisci/minimal-network.yml pull
  - docker-compose -f .travisci/minimal-network.yml up -d
  - docker stop radixdlt-js || true && docker rm radixdlt-js || true

script:
  #  Run unit and integration tests
  - docker run --network host --name radixdlt-js radixdlt-js yarn test:unit && yarn test:integration

after_success:
  # Static analyzers
  - yarn coverage
  - sonar-scanner
