
import 'mocha'
import { expect } from 'chai'

import {
    radixUniverse,
    RadixUniverse,
    RadixAccount,
    RadixLogger,
} from '../..'

before(() => {
    RadixLogger.setLevel('error')

    // Bootstrap the universe
    radixUniverse.bootstrap(RadixUniverse.LOCAL)
})

describe('RadixAccount', () => {

    it('account with known seed has expected address UID', (done) => {
        const seed = 'seed'
        const account = RadixAccount.fromSeed(Buffer.from(seed), true)

        // This is the hex-string value of the corresponding
        // RadixAddress UID generated by the Java library from
        // the UTF-8 bytes of the string "seed".
        const expectedAddressUID = 'fe1a0ad3c226be7fe3a3db2731a900ae'
        const actualAddressUID = account.address.getUID().toString()

        expect(actualAddressUID).to.equal(expectedAddressUID)

        done()
    })

    it('different accounts from same seed have same address', (done) => {
        const seed = 'seed'
        const account1 = RadixAccount.fromSeed(Buffer.from(seed), true)
        const account2 = RadixAccount.fromSeed(Buffer.from(seed), true)

        expect(account2.getAddress()).to.equal(account1.getAddress())

        done()
    })

})
